2025-05-06 21:28:41,313 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250506.txt
2025-05-06 21:28:41,316 - app.main - INFO - Civil Status Service starting up...
2025-05-06 21:28:41,316 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-06 21:28:41,316 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-06 21:28:41,316 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-06 21:28:41,387 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-06 21:28:41,390 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-06 21:28:41,391 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-06 21:32:41,431 - app.services.outbox_processor - INFO - Processing 1 outbox messages
2025-05-06 21:32:41,432 - app.services.kafka_producer - INFO - Sending marriage event to Kafka topic: btp_events
2025-05-06 21:32:41,432 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 21:32:41,432 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 21:32:41,433 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-06 21:32:41,445 - app.services.kafka_producer - INFO - Event sent successfully to topic: btp_events, partition: 0, offset: 31
2025-05-06 21:32:41,449 - app.services.outbox_processor - INFO - Successfully processed outbox message 7 (citizen_married)
2025-05-06 21:34:13,243 - app.api.router - INFO - Received request to register marriage between citizens: 001093000001 and 001294000002
2025-05-06 21:34:13,379 - httpx - INFO - HTTP Request: POST http://localhost:8000/api/v1/citizens/batch-validate "HTTP/1.1 200 OK"
2025-05-06 21:34:13,380 - app.services.marriage_validator - WARNING - Dữ liệu phả hệ không đầy đủ: Chồng 1 người, Vợ 1 người
2025-05-06 21:34:13,381 - app.api.router - INFO - Marriage validation passed. Proceeding with registration.
2025-05-06 21:34:13,392 - app.api.router - INFO - Successfully created marriage certificate with ID: 3
2025-05-06 21:34:13,402 - app.api.router - INFO - Created outbox message with ID: None
2025-05-06 21:34:21,469 - app.services.outbox_processor - INFO - Processing 1 outbox messages
2025-05-06 21:34:21,470 - app.services.kafka_producer - INFO - Sending marriage event to Kafka topic: btp_events
2025-05-06 21:34:21,474 - app.services.kafka_producer - INFO - Event sent successfully to topic: btp_events, partition: 0, offset: 32
2025-05-06 21:34:21,477 - app.services.outbox_processor - INFO - Successfully processed outbox message 8 (citizen_married)
2025-05-06 21:36:51,866 - app.api.router - INFO - Received request to register marriage between citizens: 001206000003 and 001294000002
2025-05-06 21:36:51,900 - httpx - INFO - HTTP Request: POST http://localhost:8000/api/v1/citizens/batch-validate "HTTP/1.1 200 OK"
2025-05-06 21:36:51,902 - app.services.marriage_validator - WARNING - Dữ liệu phả hệ không đầy đủ: Chồng 1 người, Vợ 1 người
2025-05-06 21:36:51,902 - app.api.router - WARNING - Marriage validation failed: Người chồng chưa đủ tuổi kết hôn (yêu cầu tối thiểu 20 tuổi, hiện tại 18 tuổi)
2025-05-06 21:37:32,551 - app.api.router - INFO - Received request to register marriage between citizens: 001085000005 and 001294000002
2025-05-06 21:37:32,582 - httpx - INFO - HTTP Request: POST http://localhost:8000/api/v1/citizens/batch-validate "HTTP/1.1 200 OK"
2025-05-06 21:37:32,583 - app.services.marriage_validator - WARNING - Dữ liệu phả hệ không đầy đủ: Chồng 1 người, Vợ 1 người
2025-05-06 21:37:32,583 - app.api.router - WARNING - Marriage validation failed: Người chồng đã kết hôn (hiện tại: Đã kết hôn)
2025-05-06 21:38:57,500 - app.api.router - INFO - Received request to register marriage between citizens: 001070000010 and 001204000011
2025-05-06 21:38:57,537 - httpx - INFO - HTTP Request: POST http://localhost:8000/api/v1/citizens/batch-validate "HTTP/1.1 200 OK"
2025-05-06 21:38:57,538 - app.services.marriage_validator - WARNING - Dữ liệu phả hệ không đầy đủ: Chồng 1 người, Vợ 2 người
2025-05-06 21:38:57,539 - app.api.router - WARNING - Marriage validation failed: Người chồng đã kết hôn (hiện tại: Đã kết hôn); Không được phép kết hôn do quan hệ huyết thống: Phát hiện quan hệ huyết thống: Người chồng là Bố của người vợ
2025-05-06 22:28:41,391 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-06 22:28:41,439 - httpx - INFO - HTTP Request: GET http://localhost:8000/api/v1/citizens/001093000001/validation "HTTP/1.1 200 OK"
2025-05-06 22:28:41,458 - httpx - INFO - HTTP Request: GET http://localhost:8000/api/v1/citizens/001294000002/validation "HTTP/1.1 200 OK"
2025-05-06 22:28:41,459 - app.services.reconciliation - WARNING - Marriage inconsistency detected: Certificate ID 3, Husband status: Độc thân, Wife status: Độc thân
2025-05-06 22:28:41,459 - app.services.reconciliation - WARNING - Found 1 marriage inconsistencies
2025-05-06 22:28:41,459 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-06 23:07:09,166 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
2025-05-06 23:07:09,167 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,167 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,167 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,168 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,168 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,168 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,269 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,270 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,271 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,271 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,271 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,372 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,372 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,375 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,375 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,375 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,475 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,476 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,477 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,477 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,477 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,578 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,578 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,585 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,585 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,585 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,686 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,686 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,687 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,687 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,687 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,788 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,788 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,796 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,796 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,796 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:09,897 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:09,897 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:09,899 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:09,899 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:09,899 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,000 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,000 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,001 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,001 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,001 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,101 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,102 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,103 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,103 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,103 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,203 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,204 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,205 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,205 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,205 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,305 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,306 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,307 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,307 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,307 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,408 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,408 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,411 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,411 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,411 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,511 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,512 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,512 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,513 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,513 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,613 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,614 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,614 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,615 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,615 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,715 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,716 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-06 23:07:10,716 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-06 23:07:10,716 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-06 23:07:10,716 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,817 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,817 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:10,817 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:10,818 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:10,937 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:10,937 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:10,937 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:10,937 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:11,144 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:11,144 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:11,145 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:11,145 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:11,502 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:11,502 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:11,502 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:11,502 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:12,154 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:12,154 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:12,154 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:12,154 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:13,734 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:13,734 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:13,734 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:13,734 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:16,752 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:16,752 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:16,752 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:16,753 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:23,835 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:23,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:23,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:23,835 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-06 23:07:38,163 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-06 23:07:38,163 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-06 23:07:38,163 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-06 23:07:38,163 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
